services:
  postgres:
    image: postgres:16
    container_name: workflows_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: workflows_user
      POSTGRES_PASSWORD: workflows_password
      POSTGRES_DB: workflows_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
